### ISSUE TITLE
Call Task not working

### ISSUE THREAD

**Issue by tulpn** [jazzband/django-queued-storage#25]
I'd like to use the DQS package in my app. However, it seems like that the task to transfer a file from local to remote is not called. I am using Django 1.8.4. 

Is there any way to test this ? 

I have also created a question on SO: http://stackoverflow.com/questions/38918751/django-queuedstorage-task-not-being-executed-when-file-is-uploaded

**Comment by ashwoods** [comment]
The link to the stackoverflow question is broken.

**Comment by ashwoods** [comment]
Closing this for now.
