### ISSUE TITLE
'QueuedStorage' object has no attribute 'generate_filename'

### ISSUE THREAD

**Issue by Clemouuche** [jazzband/django-queued-storage#31]
```python

from queued_storage.backends import QueuedS3BotoStorage
from queued_storage.fields import QueuedFileField


class Video(models.Model):
    video = QueuedFileField(storage=QueuedS3BotoStorage(delayed=True))
    thumbnail = models.FileField()
    date_taken = models.DateTimeField(auto_now_add=True)
```

I got this in the doc for the Storage class

> generate_filename(filename)[source]¶
> New in Django 1.10.
> Validates the filename by calling get_valid_name() and returns a filename to be passed to the save() method.

**Comment by melfelr** [comment]
I'm confirming the same.

**Comment by ashwoods** [comment]
Fixed in master

**Comment by Gilbishkosma** [comment]
Is it fixed? cause i am getting the same error @ashwoods

**Comment by firmprojects** [comment]
'QueuedStorage' object has no attribute 'generate_filename'. Any fix?

**Comment by Gilbishkosma** [comment]
@firmprojects  the above error is due to this issue #37  , the package is not updated since 2015.

**Comment by firmprojects** [comment]
Is there 

> @firmprojects the above error is due to this issue #37 , the package is not updated since 2015.

Is there any possible fix anywhere?

**Comment by Gilbishkosma** [comment]
@firmprojects  You can extend the QueuedStorage class and add the generate_filename method on your own.

Example:

        class CustomQueuedStorage(QueuedStorage):
                 def generate_filename(self, filename):
                        return self.get_storage(filename).generate_filename(filename)

and then use CustomQueuedStorage in your code. You can copy more missing methods from [here](https://github.com/jazzband/django-queued-storage/blob/master/queued_storage/backends.py)
